"""Device DTOs.

Schemas for the Milestone 2+ device endpoints. ``extra='forbid'`` is used
on every request model so unknown fields produce a 422 instead of being
silently dropped — keeps the API contract tight as it evolves.

The dashboard consumes these via ``contracts/openapi.json``; the Android
agent consumes them via the same JSON spec regenerated by
``scripts/export-openapi.py``.
"""

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

# Allowed capabilities — match ``app.models.device.CAPABILITIES``.
CAPABILITIES = (
    "location",
    "screenshot",
    "camera",
    "microphone",
    "screen_share",
    "contacts",
    "calendar",
    "sms",
    "notifications",
    "backup",
)
ENROLLMENT_STATES = ("pending", "active", "revoked")


# ---- Enrollment ----------------------------------------------------------


class EnrollRequestIn(BaseModel):
    """POST /devices/enroll/request body (owner side)."""

    model_config = ConfigDict(extra="forbid")

    device_name: str = Field(min_length=1, max_length=120)


class EnrollRequestOut(BaseModel):
    """POST /devices/enroll/request response.

    ``pairing_code`` is the 6-digit code the operator types or scans on
    the device. ``expires_at`` is the absolute ISO timestamp after which
    the code no longer pairs (default 10 minutes).
    """

    model_config = ConfigDict(extra="forbid")

    pairing_code: str
    device_id: str  # pre-allocated UUID; the agent submits it back
    expires_at: str


class EnrollConfirmIn(BaseModel):
    """POST /devices/enroll/confirm body (agent side).

    The agent exchanges a valid ``pairing_code`` for a credential pair.
    ``device_id`` is the pre-allocated UUID returned by ``/enroll/request``
    — it is **optional**: if omitted, the backend looks up the pending
    pairing by code and uses its reserved device_id. This keeps the phone
    flow as simple as "type the 6-digit code" when the user doesn't want
    to also paste a UUID.
    """

    model_config = ConfigDict(extra="forbid")

    pairing_code: str = Field(min_length=6, max_length=6)
    device_id: str | None = Field(default=None, min_length=36, max_length=36)
    public_key_alias: str = Field(min_length=1, max_length=120)
    hardware_model: str | None = Field(default=None, max_length=120)
    os_version: str | None = Field(default=None, max_length=60)
    app_version: str | None = Field(default=None, max_length=60)


class EnrollConfirmOut(BaseModel):
    """POST /devices/enroll/confirm response — opaque device tokens."""

    model_config = ConfigDict(extra="forbid")

    access_token: str
    refresh_token: str
    expires_in: int
    device_id: str


# ---- Heartbeat / activity ------------------------------------------------


# Percent in [0,100]; free storage in bytes ≥0.
_Pct = Annotated[int, Field(ge=0, le=100)]
_NonNegInt = Annotated[int, Field(ge=0)]


class DeviceHeartbeatIn(BaseModel):
    """POST /devices/{id}/heartbeat body."""

    model_config = ConfigDict(extra="forbid")

    battery_pct: _Pct | None = None
    network_type: str | None = Field(default=None, max_length=40)
    is_charging: bool | None = None
    free_storage_mb: _NonNegInt | None = None


class DeviceActivityEventIn(BaseModel):
    """A single event in the batch posted to /devices/{id}/activity."""

    model_config = ConfigDict(extra="forbid")

    event_type: str = Field(min_length=1, max_length=60)
    occurred_at: str | None = None
    payload: dict[str, Any] = Field(default_factory=dict)


class DeviceActivityBatchIn(BaseModel):
    """POST /devices/{id}/activity body — batched events."""

    model_config = ConfigDict(extra="forbid")

    events: list[DeviceActivityEventIn] = Field(min_length=1, max_length=200)


class InstalledAppIn(BaseModel):
    """A single row in the /devices/{id}/apps snapshot."""

    model_config = ConfigDict(extra="forbid")

    package_name: str = Field(min_length=1, max_length=255)
    app_label: str | None = Field(default=None, max_length=255)
    version_name: str | None = Field(default=None, max_length=60)
    version_code: _NonNegInt | None = None


class InstalledAppsBatchIn(BaseModel):
    """POST /devices/{id}/apps body — full snapshot."""

    model_config = ConfigDict(extra="forbid")

    apps: list[InstalledAppIn] = Field(min_length=1, max_length=2000)


# ---- Commands ------------------------------------------------------------


class CommandIn(BaseModel):
    """POST /devices/{id}/command/{capability} body.

    Every sensitive command carries a ``session_seconds`` hint so the
    agent can scope the consent and the screen-share window. The dashboard
    does NOT pre-grant consent — the agent will prompt the device owner.
    """

    model_config = ConfigDict(extra="forbid")

    session_seconds: Annotated[int, Field(ge=10, le=1800)] = 60
    reason: str | None = Field(default=None, max_length=280)
    idempotency_key: str | None = Field(default=None, max_length=64)


class CommandOut(BaseModel):
    """POST /devices/{id}/command/{capability} response."""

    model_config = ConfigDict(extra="forbid")

    command_id: str
    status: str
    expires_at: str
    consent_required: bool


# ---- Consents ------------------------------------------------------------


class DeviceConsentIn(BaseModel):
    """POST /devices/{id}/consents body — pushed from the device's UI."""

    model_config = ConfigDict(extra="forbid")

    capability: str
    expires_at: str | None = None


class DeviceConsentOut(BaseModel):
    """A single active consent for the device."""

    model_config = ConfigDict(extra="forbid")

    id: str
    capability: str
    granted_at: str
    expires_at: str | None
    revoked_at: str | None


# ---- Device reads --------------------------------------------------------


class DeviceOut(BaseModel):
    """Public device view returned by list / detail endpoints."""

    model_config = ConfigDict(extra="forbid")

    id: str
    owner_id: str
    name: str
    hardware_model: str | None
    os_version: str | None
    app_version: str | None
    battery_pct: int | None
    network_type: str | None
    enrollment_state: str
    created_at: str
    last_seen_at: str | None


class DeviceDetailOut(DeviceOut):
    """Device detail plus active consents + last activity."""

    model_config = ConfigDict(extra="forbid")

    consents: list[DeviceConsentOut] = Field(default_factory=list)
    last_activity: list[DeviceActivityEventOut] = Field(default_factory=list)


class DeviceActivityEventOut(BaseModel):
    """Append-only event row."""

    model_config = ConfigDict(extra="forbid")

    id: int
    device_id: str
    event_type: str
    occurred_at: str
    payload: dict[str, Any] = Field(default_factory=dict)


# Literal helpers — used in command routing. Pydantic v2 typing.
CapabilityLiteral = Literal[
    "screenshot",
    "screen_share",
    "locate",
    "lock",
    "ring",
]


# ---- Captures (screenshot, camera, mic) ----------------------------------


class CaptureOut(BaseModel):
    """A captured media blob (screenshot / camera snapshot / mic clip)."""

    model_config = ConfigDict(extra="forbid")

    id: str
    kind: str  # 'screenshot' | 'camera' | 'microphone'
    captured_at: str
    mime_type: str
    bytes_size: int
    # Base64 inline body — avoids MinIO dependency for this slice. The
    # dashboard decodes and renders inline; for very large captures we
    # can swap this for a signed URL later without changing the contract.
    body_b64: str


# ---- Personal data snapshots ---------------------------------------------


class ContactsSnapshotIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    contacts: list[dict[str, Any]] = Field(min_length=0, max_length=5000)


class ContactsSnapshotOut(BaseModel):
    model_config = ConfigDict(extra="forbid")

    device_id: str
    contacts: list[dict[str, Any]]
    updated_at: str | None


class CalendarSnapshotIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    events: list[dict[str, Any]] = Field(min_length=0, max_length=5000)


class CalendarSnapshotOut(BaseModel):
    model_config = ConfigDict(extra="forbid")

    device_id: str
    events: list[dict[str, Any]]
    updated_at: str | None


class SmsSnapshotIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    messages: list[dict[str, Any]] = Field(min_length=0, max_length=5000)


class SmsSnapshotOut(BaseModel):
    model_config = ConfigDict(extra="forbid")

    device_id: str
    messages: list[dict[str, Any]]
    updated_at: str | None
    restricted: bool = False  # true on Android 13+ where READ_SMS is gated


class NotificationSnapshotIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    notifications: list[dict[str, Any]] = Field(min_length=0, max_length=5000)


class NotificationSnapshotOut(BaseModel):
    model_config = ConfigDict(extra="forbid")

    device_id: str
    notifications: list[dict[str, Any]]
    updated_at: str | None


# ---- Geofences -----------------------------------------------------------


class GeofenceIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1, max_length=80)
    latitude: float = Field(ge=-90.0, le=90.0)
    longitude: float = Field(ge=-180.0, le=180.0)
    radius_meters: int = Field(ge=50, le=10_000, default=200)


class GeofenceOut(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    name: str
    latitude: float
    longitude: float
    radius_meters: int
    created_at: str
