"""Generate a fresh .env for local development.

Run from the repository root:

    python scripts/gen-secrets.py [--out backend/.env]

If the target file already exists, it is left untouched unless --force is passed.
Generates:
    JWT_SECRET_KEY
    JWT_REFRESH_SECRET_KEY
    DEFAULT_POSTGRES_PASSWORD

Secrets are 256-bit, base64-urlsafe encoded (43 chars).
"""

from __future__ import annotations

import argparse
import base64
import os
import secrets
import sys
from pathlib import Path

KEY_LEN_BYTES = 32  # 256 bits


def _gen() -> str:
    return base64.urlsafe_b64encode(secrets.token_bytes(KEY_LEN_BYTES)).decode("ascii").rstrip("=")


TEMPLATE = """# Generated by scripts/gen-secrets.py on {stamp}.
# Do not commit this file. Add it to .gitignore locally if it isn't already.

# Runtime
ENVIRONMENT=dev
LOG_LEVEL=INFO
APP_PORT=8000

# Database (matches infra/docker-compose.yml)
DATABASE_URL=postgresql+psycopg://aegisone:{db_password}@localhost:5432/aegisone
DATABASE_POOL_SIZE=10

# Redis
REDIS_URL=redis://localhost:6379/0

# Secrets (rotate separately, never share between environments)
JWT_SECRET_KEY={jwt_secret}
JWT_REFRESH_SECRET_KEY={jwt_refresh_secret}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=30

# CORS — comma-separated allowlist. Never "*" with credentials.
CORS_ORIGINS=http://localhost:3000

# Trusted reverse proxies (CIDR list). X-Forwarded-Proto is honored only from these.
TRUSTED_PROXIES=127.0.0.1/32,::1/128

# MinIO (matches infra/docker-compose.yml)
MINIO_ENDPOINT=localhost:9000
MINIO_ACCESS_KEY=aegisone
MINIO_SECRET_KEY=aegisone_dev_only
MINIO_BUCKET=aegisone

# Rate limits
RATE_LIMIT_LOGIN_PER_MIN=5
RATE_LIMIT_LOGIN_PER_EMAIL_PER_MIN=10
RATE_LIMIT_REGISTER_PER_HOUR=3
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a fresh .env for local development.")
    parser.add_argument(
        "--out",
        default="backend/.env",
        help="Path of the .env file to write (default: backend/.env).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite the existing .env file if it exists.",
    )
    args = parser.parse_args()

    target = Path(args.out).resolve()
    if target.exists() and not args.force:
        print(f"[gen-secrets] {target} already exists. Use --force to overwrite.", file=sys.stderr)
        return 0

    body = TEMPLATE.format(
        stamp=os.environ.get("GEN_SECRETS_STAMP", "dev"),
        db_password="aegisone_dev_only",
        jwt_secret=_gen(),
        jwt_refresh_secret=_gen(),
    )

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")
    print(f"[gen-secrets] wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
